# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."cadvisor" = {
    image = "gcr.io/cadvisor/cadvisor:v0.49.1";
    volumes = [
      "/:/rootfs:ro"
      "/var/run:/var/run:ro"
      "/sys:/sys:ro"
      "/var/lib/containers:/var/lib/containers:ro"
      "/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "8084:8080/tcp"
    ];
    cmd = [
      "--housekeeping_interval=10s"
      "--max_housekeeping_interval=15s" 
      "--store_container_labels=false"
      "--docker_only=false"
      "--raw_cgroup_prefix_whitelist=/system.slice/"
    ];
    log-driver = "journald";
    extraOptions = [
      "--privileged=true"
      "--network-alias=cadvisor"
      "--network=monitoring_default"
    ];
  };
  systemd.services."podman-cadvisor" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-monitoring_default.service"
    ];
    requires = [
      "podman-network-monitoring_default.service"
    ];
    partOf = [
      "podman-compose-monitoring-root.target"
    ];
    wantedBy = [
      "podman-compose-monitoring-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-monitoring_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f monitoring_default";
    };
    script = ''
      podman network inspect monitoring_default || podman network create monitoring_default
    '';
    partOf = [ "podman-compose-monitoring-root.target" ];
    wantedBy = [ "podman-compose-monitoring-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-monitoring-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}