# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."calibre" = {
    image = "lscr.io/linuxserver/calibre:latest";
    environment = {
      "CLI_ARGS" = "";
      "PASSWORD" = "";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/danielgm/Documents/Services/calibre/config:/config:rw"
    ];
    ports = [
      "8082:8080/tcp"
      "8181:8181/tcp"
      "8083:8081/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=calibre"
      "--network=calibre_default"
      "--security-opt=seccomp:unconfined"
    ];
  };
  systemd.services."podman-calibre" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-calibre_default.service"
    ];
    requires = [
      "podman-network-calibre_default.service"
    ];
    partOf = [
      "podman-compose-calibre-root.target"
    ];
    wantedBy = [
      "podman-compose-calibre-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-calibre_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f calibre_default";
    };
    script = ''
      podman network inspect calibre_default || podman network create calibre_default
    '';
    partOf = [ "podman-compose-calibre-root.target" ];
    wantedBy = [ "podman-compose-calibre-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-calibre-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
