# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."minio-minio" = {
    image = "docker.io/bitnami/minio:latest";
    cmd = [ "server" "/data" "--console-address" ":9001" ];
    environment = {
      "MINIO_DEFAULT_BUCKETS" = "stuff";
    };
    environmentFiles = [
      "/run/secrets/minio-env"
    ];
    volumes = [
      "/home/danielgm/Documents/Services/minio/minio_data:/data:rw,z"
    ];
    ports = [
      "9000:9000/tcp"
      "9001:9001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=minio"
      "--network=minio_minionetwork"
    ];
  };
  systemd.services."podman-minio-minio" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-minio_minionetwork.service"
      "minio-env-file.service"
    ];
    requires = [
      "podman-network-minio_minionetwork.service"
      "minio-env-file.service"
    ];
    partOf = [
      "podman-compose-minio-root.target"
    ];
    wantedBy = [
      "podman-compose-minio-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-minio_minionetwork" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f minio_minionetwork";
    };
    script = ''
      podman network inspect minio_minionetwork || podman network create minio_minionetwork --driver=bridge
    '';
    partOf = [ "podman-compose-minio-root.target" ];
    wantedBy = [ "podman-compose-minio-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-minio-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
