# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."windows" = {
    image = "dockurr/windows";
    environment = {
      "VERSION" = "11";
    };
    volumes = [
      "/home/danielgm/Services/windows:/storage:rw"
    ];
    ports = [
      "8006:8006/tcp"
      "3389:3389/tcp"
      "3389:3389/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/kvm:/dev/kvm:rwm"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=windows"
      "--network=windows_default"
    ];
  };
  systemd.services."podman-windows" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-windows_default.service"
    ];
    requires = [
      "podman-network-windows_default.service"
    ];
    partOf = [
      "podman-compose-windows-root.target"
    ];
    wantedBy = [
      "podman-compose-windows-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-windows_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f windows_default";
    };
    script = ''
      podman network inspect windows_default || podman network create windows_default
    '';
    partOf = [ "podman-compose-windows-root.target" ];
    wantedBy = [ "podman-compose-windows-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-windows-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
